---
- hosts: all

  tasks:
    
    - name: ldap
      pip:
        name=python-ldap
      sudo: yes
    
    - name: hit ldap with script
      shell: "echo check url is passed $ldap_server"
#  python ckanext-cfpb-authtesting/ldap_auth.py
      environment:
        ldap_server: ckan_custom_plugins.config.ckanext.ldap.uri
        ldap_user: ckan_custom_plugins.config.ckanext.ldap.auth.dn
        ldap_pass: ckan_custom_plugins.config.ckanext.ldap.auth.password
      sudo: yes
